name: Deploy live blog

on:
  push:
    branches:
      - preview
      
env:
  CF_PAGES_URL: https://preview.dylans-blog.pages.dev
  HUGO_ENV: development
      
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: Preview
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.3'
          extended: true
      - name: Build the site
        run: hugo --baseURL=$CF_PAGES_URL --environment=$HUGO_ENV
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: dylans-blog
          directory: ./public
